import { Modal } from 'bootstrap'
import Swal from 'sweetalert2'
import { ROLES } from '../utils/constants.js'
import { administrarLoteInventario, ajustarInventario, actualizarExistenciaMinima, getInventario, getLotesVencimiento, getSedesActivas, registrarEntradaInventario } from '../services/inventarioService.js'
import { actualizarProductoAdministrador, actualizarProductoOperativo, cambiarEstadoProducto, crearProducto, getProductosCatalogo } from '../services/productosService.js'
import { formatAlertState, formatCategory, formatDate, formatDateTime, formatExpiryState, formatQuantity } from '../utils/formatters.js'
import { validateNonNegativeQuantity, validatePositiveQuantity, validateProduct } from '../utils/validators.js'

const escapeHtml = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;')
const stateBadge = (state) => `<span class="status-badge status-${state}">${state === 'agotado' ? '⛔' : state === 'bajo' ? '⚠' : '✓'} ${formatAlertState(state)}</span>`
const expiryBadge = (state) => `<span class="status-badge expiry-${state}">${['vencido', 'vence_30_dias'].includes(state) ? '⚠' : '▷'} ${formatExpiryState(state)}</span>`
const metric = (label, id) => `<article class="metric-card"><span>${label}</span><strong id="${id}">—</strong></article>`
const modal = (id, title, body, label) => `<div class="modal fade" id="${id}" tabindex="-1" aria-labelledby="${id}-title" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><form id="${id}-form" novalidate><div class="modal-header"><h2 class="modal-title fs-5" id="${id}-title">${title}</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body">${body}</div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">${label}</button></div></form></div></div></div>`
const categoryOptions = '<option value="">Selecciona</option><option value="medicamento">Medicamento</option><option value="insumo">Insumo</option>'
const productFields = (prefix, admin) => `<div class="row g-3">
  ${admin ? `<div class="col-md-4"><label class="form-label" for="${prefix}-code">Código</label><input class="form-control text-uppercase" id="${prefix}-code" name="codigo" required></div>` : ''}
  <div class="col-md-${admin ? '8' : '12'}"><label class="form-label" for="${prefix}-name">Nombre</label><input class="form-control" id="${prefix}-name" name="nombre" required></div>
  <div class="col-md-4"><label class="form-label" for="${prefix}-category">Categoría</label><select class="form-select" id="${prefix}-category" name="categoria" required>${categoryOptions}</select></div>
  <div class="col-md-4"><label class="form-label" for="${prefix}-presentation">Presentación</label><input class="form-control" id="${prefix}-presentation" name="presentacion"></div>
  <div class="col-md-4"><label class="form-label" for="${prefix}-unit">Unidad de medida</label><input class="form-control" id="${prefix}-unit" name="unidadMedida" required></div>
  <div class="col-md-4"><label class="form-label" for="${prefix}-dispensing">Unidad de dispensación</label><input class="form-control" id="${prefix}-dispensing" name="unidadDispensacion"></div>
  ${admin ? `<div class="col-md-4"><label class="form-label" for="${prefix}-control">Control</label><select class="form-select" id="${prefix}-control" name="esConsumible"><option value="true">Consumible</option><option value="false">Reutilizable</option></select></div><div class="col-md-4 form-check align-self-end mb-2"><input class="form-check-input" id="${prefix}-no-discount" name="permiteSinDescuento" type="checkbox"><label class="form-check-label" for="${prefix}-no-discount">Permite registro sin descuento</label></div><div class="col-md-4 form-check align-self-end mb-2"><input class="form-check-input" id="${prefix}-active" name="activo" type="checkbox" checked><label class="form-check-label" for="${prefix}-active">Activo</label></div>` : ''}
  </div>`

export const inventarioPage = ({ session }) => {
  const admin = session.profile.rol === ROLES.ADMINISTRADOR
  const monitor = session.profile.rol === ROLES.MONITORA
  const canWrite = admin || monitor
  return `<section class="data-page"><div class="page-heading data-heading"><div><p class="eyebrow">Administración de existencias</p><h2>Inventario</h2><p class="text-muted">Productos, existencias, lotes y trazabilidad según tu acceso.</p><small id="inventory-context">Cargando sede…</small></div><div class="d-flex gap-2 flex-wrap">${admin ? '<button class="btn btn-primary" id="inventory-new" type="button">Nuevo producto</button>' : ''}<button class="btn btn-outline-primary" id="inventory-refresh" type="button">Actualizar</button></div></div>
  <div class="metrics-grid">${metric('Productos registrados','metric-total')}${metric('Disponibles','metric-normal')}${metric('Existencia baja','metric-low')}${metric('Agotados','metric-empty')}${metric('Próximos a vencer','metric-expiry')}${metric('Reutilizables','metric-reusable')}</div>
  <section id="priority-alerts" class="priority-alerts d-none" aria-labelledby="alerts-title"><h3 id="alerts-title">⚠ Alertas prioritarias</h3><div id="priority-alert-list"></div></section>
  <section class="data-panel"><h3>Filtros</h3><form id="inventory-filters" class="row g-3"><div class="col-md-4"><label class="form-label" for="inventory-search">Código o producto</label><input class="form-control" id="inventory-search" name="busqueda"></div><div class="col-md-4"><label class="form-label" for="inventory-site">Sede</label><select class="form-select" id="inventory-site" name="sedeId" ${monitor ? 'disabled' : ''}><option value="">Todas las sedes</option></select></div><div class="col-md-4"><label class="form-label" for="inventory-category">Categoría</label><select class="form-select" id="inventory-category" name="categoria"><option value="">Todas</option><option value="medicamento">Medicamento</option><option value="insumo">Insumo</option></select></div><div class="col-md-4"><label class="form-label" for="inventory-state">Estado</label><select class="form-select" id="inventory-state" name="estadoAlerta"><option value="">Todos</option><option value="normal">Normal</option><option value="bajo">Bajo</option><option value="agotado">Agotado</option></select></div><div class="col-md-4"><label class="form-label" for="inventory-control">Tipo</label><select class="form-select" id="inventory-control" name="tipoControl"><option value="">Todos</option><option value="consumible">Consumible</option><option value="reutilizable">Reutilizable</option></select></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary" id="inventory-apply" type="submit">Aplicar filtros</button><button class="btn btn-outline-secondary" id="inventory-clear" type="button">Limpiar filtros</button></div></form></section>
  <div class="nav nav-tabs mb-3" role="tablist"><button class="nav-link active" data-inventory-tab="stock" type="button">Existencias</button><button class="nav-link" data-inventory-tab="expiry" type="button">Vencimientos</button></div>
  <section id="stock-panel" class="data-panel"><div id="inventory-status" class="loading-state" aria-live="polite">Consultando inventario…</div><div id="inventory-results"></div><div id="inventory-pagination" class="pagination-bar"></div></section><section id="expiry-panel" class="data-panel d-none"><div class="row mb-3"><div class="col-md-4"><label class="form-label" for="expiry-state">Estado de vencimiento</label><select class="form-select" id="expiry-state"><option value="">Todos</option><option value="vencido">Vencido</option><option value="vence_30_dias">Vence en 30 días</option><option value="vence_90_dias">Vence en 90 días</option><option value="vigente">Vigente</option><option value="sin_fecha">Sin fecha</option></select></div></div><div id="expiry-status" class="loading-state" aria-live="polite"></div><div id="expiry-results"></div></section>
  ${admin ? modal('product-create', 'Nuevo producto', productFields('create', true), 'Crear producto') : ''}
  ${canWrite ? modal('product-edit', 'Editar producto', `<input type="hidden" name="productoId"><input type="hidden" name="sedeId"><input type="hidden" name="loteId">${!admin ? '<div class="alert alert-warning">Nombre, categoría, presentación y unidades son datos globales: el cambio se verá en todas las sedes.</div>' : ''}${productFields('edit', admin)}<hr><h3 class="fs-6">Datos de esta sede</h3><div class="row g-3"><div class="col-md-3"><label class="form-label">Existencia actual</label><input class="form-control" name="existenciaActual" readonly></div><div class="col-md-3"><label class="form-label">Existencia mínima</label><input class="form-control" name="existenciaMinima" type="number" min="0" step="0.01"></div><div class="col-md-3"><label class="form-label">Lote</label><input class="form-control" name="numeroLote"></div><div class="col-md-3"><label class="form-label">Vencimiento</label><input class="form-control" name="fechaVencimiento" type="date"></div><div class="col-12"><label class="form-label">Observaciones del lote</label><textarea class="form-control" name="observacionesLote" rows="2"></textarea></div></div>`, 'Guardar cambios') : ''}
  ${canWrite ? modal('inventory-entry', 'Registrar entrada', `<div class="row g-3"><div class="col-md-6"><label class="form-label">Producto</label><select class="form-select" name="productoId" required></select></div><div class="col-md-6"><label class="form-label">Sede</label><select class="form-select" name="sedeId" ${monitor ? 'disabled' : ''} required></select></div><div class="col-md-4"><label class="form-label">Cantidad</label><input class="form-control" name="cantidad" type="number" min="0.01" step="0.01" required></div><div class="col-md-4"><label class="form-label">Número de lote</label><input class="form-control" name="numeroLote"></div><div class="col-md-4"><label class="form-label">Vencimiento</label><input class="form-control" name="fechaVencimiento" type="date"></div><div class="col-12"><label class="form-label">Observaciones</label><textarea class="form-control" name="observaciones" rows="2"></textarea></div><div class="col-12 text-muted small">Fecha/hora y responsable se registran automáticamente desde la sesión.</div></div>`, 'Registrar entrada') : ''}
  ${admin ? modal('inventory-adjust', 'Ajustar existencia', `<input type="hidden" name="productoId"><input type="hidden" name="sedeId"><div class="row g-3"><div class="col-md-6"><label class="form-label">Producto</label><input class="form-control" name="producto" readonly></div><div class="col-md-6"><label class="form-label">Sede</label><input class="form-control" name="sede" readonly></div><div class="col-md-4"><label class="form-label">Existencia actual</label><input class="form-control" name="existenciaActual" readonly></div><div class="col-md-4"><label class="form-label">Tipo de ajuste</label><select class="form-select" name="tipoAjuste"><option value="ajuste_positivo">Aumento</option><option value="ajuste_negativo">Disminución</option></select></div><div class="col-md-4"><label class="form-label">Cantidad</label><input class="form-control" name="cantidad" type="number" min="0.01" step="0.01" required></div><div class="col-12"><label class="form-label">Motivo</label><input class="form-control" name="motivo" required></div><div class="col-12"><label class="form-label">Observaciones</label><textarea class="form-control" name="observaciones" rows="2"></textarea></div></div>`, 'Registrar ajuste') : ''}</section>`
}

export const initInventarioPage = async ({ session }) => {
  const root = document.querySelector('.data-page'); if (!root) return
  const admin = session.profile.rol === ROLES.ADMINISTRADOR; const monitor = session.profile.rol === ROLES.MONITORA; const canWrite = admin || monitor
  const $ = (id) => root.querySelector(`#${id}`); const pageSize = 20
  let rows = []; let lots = []; let sites = []; let products = []; let page = 1; let loading = false
  const modals = {}
  if (admin) { modals.create = Modal.getOrCreateInstance($('product-create')); modals.adjust = Modal.getOrCreateInstance($('inventory-adjust')) }
  if (canWrite) { modals.edit = Modal.getOrCreateInstance($('product-edit')); modals.entry = Modal.getOrCreateInstance($('inventory-entry')) }
  const selectedSite = () => monitor ? session.profile.sede_id : $('inventory-site').value
  const siteOptions = (includeAll = false) => `${includeAll ? '<option value="">Todas las sedes</option>' : '<option value="">Selecciona</option>'}${sites.map((x) => `<option value="${x.id}">${escapeHtml(x.nombre)}</option>`).join('')}`
  const productOptions = () => `<option value="">Selecciona</option>${products.filter((x) => x.estado === 'activo').map((x) => `<option value="${x.id}">${escapeHtml(x.codigo)} · ${escapeHtml(x.nombre)}</option>`).join('')}`
  const safeLog = (action, error) => console.error({ action, code: error?.code, message: error?.message, status: error?.status })
  const friendlyError = (error, fallback) => error?.code === '23505' ? 'Ya existe un registro con esos datos.' : error?.code === '42501' || /permiso|autorizad/i.test(error?.message || '') ? 'No tienes permiso para modificar esta sede.' : /negativa/i.test(error?.message || '') ? 'La existencia no puede quedar negativa.' : error?.message || fallback
  const setBusy = (form, busy, text = 'Guardando…') => { const button = form.querySelector('[type="submit"]'); if (!button) return; if (!button.dataset.label) button.dataset.label = button.textContent; button.disabled = busy; button.textContent = busy ? text : button.dataset.label }
  const values = (form) => { const value = Object.fromEntries(new FormData(form)); value.esConsumible = value.esConsumible === 'true'; value.permiteSinDescuento = form.elements.permiteSinDescuento?.checked ?? false; value.activo = form.elements.activo?.checked ?? true; return value }
  const lotFor = (row) => lots.find((lot) => String(lot.producto_id) === String(row.producto_id) && String(lot.sede_id) === String(row.sede_id))
  const actions = (row, index) => { if (!canWrite) return '—'; const edit = (admin || row.sede_id) ? `<button class="btn btn-sm btn-outline-primary" data-action="edit" data-index="${index}">Editar</button>` : ''; const entry = row.estado === 'activo' ? `<button class="btn btn-sm btn-outline-success" data-action="entry" data-index="${index}">Registrar entrada</button>` : ''; const adjust = admin && row.sede_id ? `<button class="btn btn-sm btn-outline-warning" data-action="adjust" data-index="${index}">Ajustar existencia</button>` : ''; const active = admin ? `<button class="btn btn-sm btn-outline-secondary" data-action="active" data-index="${index}">${row.estado === 'activo' ? 'Desactivar' : 'Activar'}</button>` : ''; return `<div class="d-flex flex-wrap gap-1">${edit}${entry}${adjust}${active}</div>` }
  const renderMetrics = () => { $('metric-total').textContent = new Set(rows.map((x) => x.producto_id)).size; $('metric-normal').textContent = rows.filter((x) => x.estado_alerta === 'normal').length; $('metric-low').textContent = rows.filter((x) => x.estado_alerta === 'bajo').length; $('metric-empty').textContent = rows.filter((x) => x.estado_alerta === 'agotado').length; $('metric-expiry').textContent = lots.filter((x) => ['vence_30_dias','vence_90_dias'].includes(x.estado_vencimiento)).length; $('metric-reusable').textContent = rows.filter((x) => !x.es_consumible || x.permite_registro_sin_descuento).length; const alerts = [...rows.filter((x) => ['agotado','bajo'].includes(x.estado_alerta)).slice(0,5), ...lots.filter((x) => ['vencido','vence_30_dias'].includes(x.estado_vencimiento)).slice(0,5)]; $('priority-alerts').classList.toggle('d-none', !alerts.length); $('priority-alert-list').innerHTML = alerts.map((x) => `<p>${x.estado_alerta ? stateBadge(x.estado_alerta) : expiryBadge(x.estado_vencimiento)} <strong>${escapeHtml(x.nombre || x.producto)}</strong> · ${escapeHtml(x.sede || 'Sin asignar')}</p>`).join('') }
  const renderInventory = () => { const start = (page - 1) * pageSize; const visible = rows.slice(start, start + pageSize); $('inventory-status').textContent = rows.length ? `${rows.length} registro(s) encontrados.` : 'No hay registros que coincidan con los filtros.'; $('inventory-results').innerHTML = visible.length ? `<div class="desktop-table"><table class="table align-middle"><thead><tr><th>Código</th><th>Producto</th><th>Categoría</th><th>Presentación</th><th>Sede</th><th>Actual</th><th>Mínima</th><th>Estado</th><th>Lote</th><th>Vencimiento</th><th>Tipo</th><th>Acciones</th></tr></thead><tbody>${visible.map((x,i) => { const lot = lotFor(x); const index = start+i; return `<tr><td>${escapeHtml(x.codigo)}</td><td>${escapeHtml(x.nombre)} ${x.estado === 'inactivo' ? '<span class="status-badge status-agotado">Inactivo</span>' : ''}</td><td>${formatCategory(x.categoria)}</td><td>${escapeHtml(x.presentacion || '—')}</td><td>${escapeHtml(x.sede || 'Sin asignar')}</td><td>${x.sede_id ? formatQuantity(x.existencia_actual) : '—'}</td><td>${x.sede_id ? formatQuantity(x.existencia_minima) : '—'}</td><td>${x.sede_id ? stateBadge(x.estado_alerta) : 'Sin asignar'}</td><td>${escapeHtml(lot?.numero_lote || '—')}</td><td>${formatDate(lot?.fecha_vencimiento)}</td><td>${!x.es_consumible || x.permite_registro_sin_descuento ? 'Reutilizable / sin descuento' : 'Consumible'}</td><td>${actions(x,index)}</td></tr>` }).join('')}</tbody></table></div><div class="mobile-cards">${visible.map((x,i) => { const lot = lotFor(x); return `<article class="data-card"><h4>${escapeHtml(x.codigo)} · ${escapeHtml(x.nombre)}</h4><p>${escapeHtml(x.sede || 'Sin asignar')} · ${formatCategory(x.categoria)}</p><dl><div><dt>Existencia</dt><dd>${x.sede_id ? `${formatQuantity(x.existencia_actual)} / mín. ${formatQuantity(x.existencia_minima)}` : 'Sin asignar'}</dd></div><div><dt>Lote / vencimiento</dt><dd>${escapeHtml(lot?.numero_lote || '—')} · ${formatDate(lot?.fecha_vencimiento)}</dd></div></dl>${x.sede_id ? stateBadge(x.estado_alerta) : ''}${actions(x,start+i)}</article>` }).join('')}</div>` : ''; const pages = Math.ceil(rows.length/pageSize); $('inventory-pagination').innerHTML = pages > 1 ? `<button class="btn btn-sm btn-outline-secondary" data-page="${page-1}" ${page===1?'disabled':''}>Anterior</button><span>Página ${page} de ${pages}</span><button class="btn btn-sm btn-outline-secondary" data-page="${page+1}" ${page===pages?'disabled':''}>Siguiente</button>` : '' }
  const renderLots = () => { const filter = $('expiry-state').value; const visible = lots.filter((x) => !filter || x.estado_vencimiento === filter); $('expiry-status').textContent = visible.length ? `${visible.length} lote(s) encontrados.` : 'No hay vencimientos que coincidan con el filtro.'; $('expiry-results').innerHTML = visible.length ? `<div class="desktop-table"><table class="table align-middle"><thead><tr><th>Producto</th><th>Sede</th><th>Lote</th><th>Vencimiento</th><th>Cantidad</th><th>Estado</th></tr></thead><tbody>${visible.map((x) => `<tr><td>${escapeHtml(x.producto)}</td><td>${escapeHtml(x.sede)}</td><td>${escapeHtml(x.numero_lote || 'Sin número')}</td><td>${formatDate(x.fecha_vencimiento)}</td><td>${formatQuantity(x.cantidad_disponible)}</td><td>${expiryBadge(x.estado_vencimiento)}</td></tr>`).join('')}</tbody></table></div>` : '' }
  const load = async () => { if (loading) return; loading = true; $('inventory-refresh').disabled = true; $('inventory-apply').disabled = true; try { const filters = Object.fromEntries(new FormData($('inventory-filters'))); filters.sedeId = selectedSite(); filters.incluirInactivos = admin; [rows,lots,products] = await Promise.all([getInventario(filters),getLotesVencimiento({sedeId:filters.sedeId}),getProductosCatalogo({incluirInactivos:admin})]); if (admin && !filters.sedeId) { const assigned = new Set(rows.map((x)=>x.producto_id)); rows.push(...products.filter((x)=>!assigned.has(x.id)).map((x)=>({ ...x, producto_id:x.id, sede_id:null, sede:null, existencia_actual:null, existencia_minima:null, estado_alerta:null }))) } page=1; renderMetrics(); renderInventory(); renderLots(); const site=sites.find((x)=>String(x.id)===String(filters.sedeId)); $('inventory-context').textContent=`${site?.nombre||'Todas las sedes'} · Actualizado ${formatDateTime(new Date())}` } catch(error) { safeLog('consultar_inventario',error); $('inventory-status').textContent='No fue posible consultar el inventario.'; $('inventory-results').innerHTML='' } finally { loading=false; $('inventory-refresh').disabled=false; $('inventory-apply').disabled=false } }
  try { sites=await getSedesActivas(); $('inventory-site').innerHTML=siteOptions(true); if(monitor)$('inventory-site').value=session.profile.sede_id||''; if(canWrite){ const entry=$('inventory-entry-form'); entry.elements.sedeId.innerHTML=siteOptions(); if(monitor)entry.elements.sedeId.value=session.profile.sede_id||'' } } catch(error){safeLog('consultar_sedes',error);$('inventory-status').textContent='No fue posible consultar las sedes.';return}
  $('inventory-filters').addEventListener('submit',(event)=>{event.preventDefault();load()}); $('inventory-refresh').addEventListener('click',load); $('inventory-clear').addEventListener('click',()=>{$('inventory-filters').reset();if(monitor)$('inventory-site').value=session.profile.sede_id||'';load()}); $('inventory-pagination').addEventListener('click',(event)=>{const next=event.target.closest('[data-page]')?.dataset.page;if(!next)return;page=Number(next);renderInventory()}); $('expiry-state').addEventListener('change',renderLots)
  root.querySelectorAll('[data-inventory-tab]').forEach((button)=>button.addEventListener('click',()=>{root.querySelectorAll('[data-inventory-tab]').forEach((x)=>x.classList.toggle('active',x===button));$('stock-panel').classList.toggle('d-none',button.dataset.inventoryTab!=='stock');$('expiry-panel').classList.toggle('d-none',button.dataset.inventoryTab!=='expiry')}))
  if(admin) $('inventory-new').addEventListener('click',()=>{$('product-create-form').reset();$('product-create-form').elements.activo.checked=true;modals.create.show()})
  if(canWrite) root.addEventListener('click',async(event)=>{const button=event.target.closest('[data-action]');if(!button)return;const row=rows[Number(button.dataset.index)];if(!row)return; if(button.dataset.action==='entry'){const form=$('inventory-entry-form');form.reset();form.elements.productoId.innerHTML=productOptions();form.elements.productoId.value=row.producto_id;if(monitor)form.elements.sedeId.value=session.profile.sede_id||'';else form.elements.sedeId.value=row.sede_id||'';modals.entry.show();return} if(button.dataset.action==='edit'){const form=$('product-edit-form');form.reset();const lot=lotFor(row); Object.assign(form.elements.productoId,{value:row.producto_id});form.elements.sedeId.value=row.sede_id;form.elements.nombre.value=row.nombre||'';form.elements.categoria.value=row.categoria||'';form.elements.presentacion.value=row.presentacion||'';form.elements.unidadMedida.value=row.unidad_medida||'';form.elements.unidadDispensacion.value=row.unidad_dispensacion||'';form.elements.existenciaActual.value=row.existencia_actual;form.elements.existenciaMinima.value=row.existencia_minima;form.elements.loteId.value=lot?.id||'';form.elements.numeroLote.value=lot?.numero_lote||'';form.elements.fechaVencimiento.value=lot?.fecha_vencimiento||'';form.elements.observacionesLote.value=lot?.observaciones||'';if(admin){form.elements.codigo.value=row.codigo;form.elements.esConsumible.value=String(Boolean(row.es_consumible));form.elements.permiteSinDescuento.checked=Boolean(row.permite_registro_sin_descuento);form.elements.activo.checked=row.estado==='activo'}modals.edit.show();return} if(button.dataset.action==='adjust'){const form=$('inventory-adjust-form');form.reset();form.elements.productoId.value=row.producto_id;form.elements.sedeId.value=row.sede_id;form.elements.producto.value=`${row.codigo} · ${row.nombre}`;form.elements.sede.value=row.sede;form.elements.existenciaActual.value=row.existencia_actual;modals.adjust.show();return} if(button.dataset.action==='active'){const next=row.estado!=='activo';const confirmation=await Swal.fire({icon:'warning',title:next?'Activar producto':'Desactivar producto',text:next?'El producto volverá a estar disponible para nuevas atenciones.':'Dejará de estar disponible para nuevas atenciones. El historial se conservará.',showCancelButton:true,confirmButtonText:next?'Activar':'Desactivar',cancelButtonText:'Cancelar'});if(!confirmation.isConfirmed)return;button.disabled=true;try{await cambiarEstadoProducto(row.producto_id,next);await load();Swal.fire({icon:'success',title:next?'Producto activado':'Producto desactivado'})}catch(error){safeLog('cambiar_estado_producto',error);Swal.fire({icon:'error',title:'No fue posible actualizar el producto.',text:friendlyError(error,'No fue posible actualizar el producto.')});button.disabled=false}} })
  const bindSubmit = (id, action, fallback) => { const form=$(id); if(!form)return; form.addEventListener('submit',async(event)=>{event.preventDefault();if(form.dataset.busy==='true')return;form.dataset.busy='true';setBusy(form,true);try{await action(form);form.reset();Modal.getInstance(form.closest('.modal'))?.hide();await load()}catch(error){if(!error?.cancelled){safeLog(id,error);await Swal.fire({icon:'error',title:fallback,text:friendlyError(error,fallback)})}}finally{form.dataset.busy='false';setBusy(form,false)}}) }
  bindSubmit('product-create-form',async(form)=>{const data=values(form);if(Object.keys(validateProduct(data,{admin:true})).length)throw new Error('Completa código, nombre, categoría y unidad de medida.');await crearProducto(data);await Swal.fire({icon:'success',title:'Producto creado'})},'No fue posible crear el producto.')
  bindSubmit('product-edit-form',async(form)=>{const data=values(form);if(Object.keys(validateProduct(data,{admin})).length)throw new Error('Completa los campos obligatorios.');if(admin)await actualizarProductoAdministrador(data);else await actualizarProductoOperativo(data);if(data.sedeId){if(!validateNonNegativeQuantity(data.existenciaMinima))throw new Error('La existencia mínima no puede ser negativa.');await actualizarExistenciaMinima({productoId:data.productoId,sedeId:data.sedeId,existenciaMinima:data.existenciaMinima});if(data.loteId)await administrarLoteInventario({loteId:data.loteId,productoId:data.productoId,sedeId:data.sedeId,numeroLote:data.numeroLote,fechaVencimiento:data.fechaVencimiento,observaciones:data.observacionesLote})}await Swal.fire({icon:'success',title:'Producto actualizado'})},'No fue posible actualizar el producto.')
  bindSubmit('inventory-entry-form',async(form)=>{const data=values(form);data.sedeId=monitor?session.profile.sede_id:data.sedeId;if(!validatePositiveQuantity(data.cantidad))throw new Error('La cantidad debe ser mayor que cero.');const product=products.find((x)=>String(x.id)===String(data.productoId));const site=sites.find((x)=>String(x.id)===String(data.sedeId));const confirmation=await Swal.fire({icon:'question',title:'Confirmar entrada',text:`Se registrarán ${formatQuantity(data.cantidad)} unidades de ${product?.nombre||'el producto'} en ${site?.nombre||'la sede'}.`,showCancelButton:true,confirmButtonText:'Registrar entrada',cancelButtonText:'Cancelar'});if(!confirmation.isConfirmed)throw Object.assign(new Error('Operación cancelada.'),{cancelled:true});await registrarEntradaInventario(data);await Swal.fire({icon:'success',title:'Entrada registrada'})},'No fue posible registrar la entrada.')
  bindSubmit('inventory-adjust-form',async(form)=>{const data=values(form);if(!validatePositiveQuantity(data.cantidad)||!String(data.motivo||'').trim())throw new Error('Cantidad positiva y motivo son obligatorios.');if(data.tipoAjuste==='ajuste_negativo'&&Number(data.cantidad)>Number(data.existenciaActual))throw new Error('La existencia no puede quedar negativa.');const text=data.tipoAjuste==='ajuste_negativo'?`Se descontarán ${formatQuantity(data.cantidad)} unidades por ajuste administrativo.`:`Se agregarán ${formatQuantity(data.cantidad)} unidades por ajuste administrativo.`;const confirmation=await Swal.fire({icon:'warning',title:'Confirmar ajuste',text,showCancelButton:true,confirmButtonText:'Registrar ajuste',cancelButtonText:'Cancelar'});if(!confirmation.isConfirmed)throw Object.assign(new Error('Operación cancelada.'),{cancelled:true});await ajustarInventario(data);await Swal.fire({icon:'success',title:'Ajuste registrado'})},'No fue posible ajustar la existencia.')
  await load()
  if(canWrite){const form=$('inventory-entry-form');form.elements.productoId.innerHTML=productOptions()}
}
