import { ROLES } from '../utils/constants.js'
import { getInventario, getLotesVencimiento, getSedesActivas } from '../services/inventarioService.js'
import { formatAlertState, formatCategory, formatDate, formatDateTime, formatExpiryState, formatQuantity } from '../utils/formatters.js'

const escapeHtml = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;')
const stateBadge = (state) => `<span class="status-badge status-${state}">${state === 'agotado' ? '⛔' : state === 'bajo' ? '⚠' : '✓'} ${formatAlertState(state)}</span>`
const expiryBadge = (state) => `<span class="status-badge expiry-${state}">${['vencido', 'vence_30_dias'].includes(state) ? '⚠' : '◷'} ${formatExpiryState(state)}</span>`
const metric = (label, id) => `<article class="metric-card"><span>${label}</span><strong id="${id}">—</strong></article>`

export const inventarioPage = ({ session }) => {
  const monitor = session.profile.rol === ROLES.MONITORA
  return `<section class="data-page"><div class="page-heading data-heading"><div><p class="eyebrow">Consulta de existencias</p><h2>Inventario</h2><p class="text-muted">Existencias, alertas y vencimientos disponibles según tu acceso.</p><small id="inventory-context">Cargando sede…</small></div><button class="btn btn-outline-primary" id="inventory-refresh" type="button">Actualizar</button></div>
  <div class="metrics-grid">${metric('Total de productos registrados','metric-total')}${metric('Productos disponibles','metric-normal')}${metric('Existencia baja','metric-low')}${metric('Productos agotados','metric-empty')}${metric('Próximos a vencer','metric-expiry')}${metric('Reutilizables','metric-reusable')}</div>
  <section id="priority-alerts" class="priority-alerts d-none" aria-labelledby="alerts-title"><h3 id="alerts-title">⚠ Alertas prioritarias</h3><div id="priority-alert-list"></div></section>
  <section class="data-panel"><h3>Filtros</h3><form id="inventory-filters" class="row g-3">
    <div class="col-md-4"><label class="form-label" for="inventory-search">Código o nombre</label><input class="form-control" id="inventory-search" name="busqueda"></div>
    <div class="col-md-4"><label class="form-label" for="inventory-site">Sede</label><select class="form-select" id="inventory-site" name="sedeId" ${monitor ? 'disabled' : ''}><option value="">Todas las sedes</option></select></div>
    <div class="col-md-4"><label class="form-label" for="inventory-category">Categoría</label><select class="form-select" id="inventory-category" name="categoria"><option value="">Todas</option><option value="medicamento">Medicamento</option><option value="insumo">Insumo</option></select></div>
    <div class="col-md-4"><label class="form-label" for="inventory-state">Estado</label><select class="form-select" id="inventory-state" name="estadoAlerta"><option value="">Todos</option><option value="normal">Normal</option><option value="bajo">Bajo</option><option value="agotado">Agotado</option></select></div>
    <div class="col-md-4"><label class="form-label" for="inventory-control">Control</label><select class="form-select" id="inventory-control" name="tipoControl"><option value="">Todos</option><option value="consumible">Consumible</option><option value="reutilizable">Reutilizable</option></select></div>
    <div class="col-md-4 d-flex align-items-end"><button class="btn btn-outline-secondary w-100" id="inventory-clear" type="button">Limpiar filtros</button></div>
  </form></section>
  <div class="nav nav-tabs mb-3" role="tablist"><button class="nav-link active" data-inventory-tab="stock" type="button">Existencias</button><button class="nav-link" data-inventory-tab="expiry" type="button">Vencimientos</button></div>
  <section id="stock-panel" class="data-panel"><div id="inventory-status" class="loading-state" aria-live="polite">Consultando inventario…</div><div id="inventory-results"></div><div id="inventory-pagination" class="pagination-bar"></div></section>
  <section id="expiry-panel" class="data-panel d-none"><div class="row mb-3"><div class="col-md-4"><label class="form-label" for="expiry-state">Estado de vencimiento</label><select class="form-select" id="expiry-state"><option value="">Todos</option><option value="vencido">Vencido</option><option value="vence_30_dias">Vence en 30 días</option><option value="vence_90_dias">Vence en 90 días</option><option value="vigente">Vigente</option><option value="sin_fecha">Sin fecha</option></select></div></div><div id="expiry-status" class="loading-state" aria-live="polite"></div><div id="expiry-results"></div></section></section>`
}

export const initInventarioPage = async ({ session }) => {
  const root = document.querySelector('.data-page'); if (!root) return
  const monitor = session.profile.rol === ROLES.MONITORA; const pageSize = 20
  let rows = []; let lots = []; let page = 1; let loading = false; let sites = []
  const $ = (id) => root.querySelector(`#${id}`)
  const selectedSite = () => monitor ? session.profile.sede_id : $('inventory-site').value
  const renderMetrics = () => {
    $('metric-total').textContent = rows.length; $('metric-normal').textContent = rows.filter((x) => x.estado_alerta === 'normal').length; $('metric-low').textContent = rows.filter((x) => x.estado_alerta === 'bajo').length; $('metric-empty').textContent = rows.filter((x) => x.estado_alerta === 'agotado').length; $('metric-expiry').textContent = lots.filter((x) => ['vence_30_dias','vence_90_dias'].includes(x.estado_vencimiento)).length; $('metric-reusable').textContent = rows.filter((x) => !x.es_consumible || x.permite_registro_sin_descuento).length
    const alerts = [...rows.filter((x) => ['agotado','bajo'].includes(x.estado_alerta)).slice(0, 5), ...lots.filter((x) => ['vencido','vence_30_dias'].includes(x.estado_vencimiento)).slice(0, 5)]
    $('priority-alerts').classList.toggle('d-none', !alerts.length); $('priority-alert-list').innerHTML = alerts.slice(0, 8).map((x) => `<p>${x.estado_alerta ? stateBadge(x.estado_alerta) : expiryBadge(x.estado_vencimiento)} <strong>${escapeHtml(x.nombre || x.producto)}</strong> · ${escapeHtml(x.sede)}</p>`).join('')
  }
  const renderInventory = () => {
    const start = (page - 1) * pageSize; const visible = rows.slice(start, start + pageSize)
    const filters = Object.fromEntries(new FormData($('inventory-filters'))); const hasFilters = filters.busqueda || filters.categoria || filters.estadoAlerta || filters.tipoControl
    $('inventory-status').textContent = rows.length ? `${rows.length} registro(s) encontrados.` : hasFilters ? 'No hay productos que coincidan con los filtros.' : 'No hay inventario registrado para esta sede.'
    $('inventory-results').innerHTML = visible.length ? `<div class="desktop-table"><table class="table align-middle"><thead><tr><th>Código</th><th>Producto</th><th>Categoría</th><th>Presentación</th><th>Unidad</th><th>Sede</th><th>Actual</th><th>Mínima</th><th>Tipo</th><th>Estado</th></tr></thead><tbody>${visible.map((x) => `<tr><td>${escapeHtml(x.codigo)}</td><td>${escapeHtml(x.nombre)}</td><td>${formatCategory(x.categoria)}</td><td>${escapeHtml(x.presentacion || '—')}</td><td>${escapeHtml(x.unidad_dispensacion || x.unidad_medida)}</td><td>${escapeHtml(x.sede)}</td><td>${formatQuantity(x.existencia_actual)}</td><td>${formatQuantity(x.existencia_minima)}</td><td>${!x.es_consumible || x.permite_registro_sin_descuento ? 'Reutilizable / sin descuento' : 'Consumible'}</td><td>${stateBadge(x.estado_alerta)}</td></tr>`).join('')}</tbody></table></div><div class="mobile-cards">${visible.map((x) => `<article class="data-card"><h4>${escapeHtml(x.codigo)} · ${escapeHtml(x.nombre)}</h4><p>${escapeHtml(x.sede)} · ${formatCategory(x.categoria)}</p><dl><div><dt>Existencia</dt><dd>${formatQuantity(x.existencia_actual)} / mín. ${formatQuantity(x.existencia_minima)}</dd></div><div><dt>Tipo</dt><dd>${!x.es_consumible || x.permite_registro_sin_descuento ? 'Reutilizable / sin descuento' : 'Consumible'}</dd></div></dl>${stateBadge(x.estado_alerta)}</article>`).join('')}</div>` : ''
    const pages = Math.ceil(rows.length / pageSize); $('inventory-pagination').innerHTML = pages > 1 ? `<button class="btn btn-sm btn-outline-secondary" data-page="${page - 1}" ${page === 1 ? 'disabled' : ''}>Anterior</button><span>Página ${page} de ${pages}</span><button class="btn btn-sm btn-outline-secondary" data-page="${page + 1}" ${page === pages ? 'disabled' : ''}>Siguiente</button>` : ''
  }
  const renderLots = () => { const filter = $('expiry-state').value; const visible = lots.filter((x) => !filter || x.estado_vencimiento === filter); $('expiry-status').textContent = visible.length ? `${visible.length} lote(s) encontrados.` : 'No hay vencimientos que coincidan con el filtro.'; $('expiry-results').innerHTML = visible.length ? `<div class="desktop-table"><table class="table align-middle"><thead><tr><th>Producto</th><th>Sede</th><th>Lote</th><th>Vencimiento</th><th>Cantidad</th><th>Estado</th></tr></thead><tbody>${visible.map((x) => `<tr><td>${escapeHtml(x.producto)}</td><td>${escapeHtml(x.sede)}</td><td>${escapeHtml(x.numero_lote || 'Sin número')}</td><td>${formatDate(x.fecha_vencimiento)}</td><td>${formatQuantity(x.cantidad_disponible)}</td><td>${expiryBadge(x.estado_vencimiento)}</td></tr>`).join('')}</tbody></table></div><div class="mobile-cards">${visible.map((x) => `<article class="data-card"><h4>${escapeHtml(x.producto)}</h4><p>${escapeHtml(x.sede)} · Lote ${escapeHtml(x.numero_lote || 'sin número')}</p><p>${formatDate(x.fecha_vencimiento)} · ${formatQuantity(x.cantidad_disponible)}</p>${expiryBadge(x.estado_vencimiento)}</article>`).join('')}</div>` : '' }
  const load = async () => {
    if (loading) return; loading = true; $('inventory-refresh').disabled = true; $('inventory-status').textContent = 'Consultando inventario…'
    try { const filters = Object.fromEntries(new FormData($('inventory-filters'))); filters.sedeId = selectedSite(); [rows, lots] = await Promise.all([getInventario(filters), getLotesVencimiento({ sedeId: filters.sedeId })]); page = 1; renderMetrics(); renderInventory(); renderLots(); const site = sites.find((x) => String(x.id) === String(filters.sedeId)); $('inventory-context').textContent = `${site?.nombre || 'Todas las sedes'} · Actualizado ${formatDateTime(new Date())}` }
    catch { $('inventory-status').textContent = 'No fue posible consultar el inventario.'; $('inventory-results').innerHTML = '' }
    finally { loading = false; $('inventory-refresh').disabled = false }
  }
  try { sites = await getSedesActivas(); $('inventory-site').innerHTML = `<option value="">Todas las sedes</option>${sites.map((x) => `<option value="${x.id}">${escapeHtml(x.nombre)}</option>`).join('')}`; if (monitor) $('inventory-site').value = session.profile.sede_id || '' } catch { $('inventory-status').textContent = 'No fue posible consultar las sedes.'; return }
  $('inventory-filters').addEventListener('change', load); let searchTimer; $('inventory-search').addEventListener('input', () => { clearTimeout(searchTimer); searchTimer = setTimeout(load, 350) }); $('inventory-refresh').addEventListener('click', load); $('inventory-clear').addEventListener('click', () => { $('inventory-filters').reset(); if (monitor) $('inventory-site').value = session.profile.sede_id || ''; load() }); $('inventory-pagination').addEventListener('click', (e) => { if (!e.target.dataset.page) return; page = Number(e.target.dataset.page); renderInventory() }); $('expiry-state').addEventListener('change', renderLots)
  root.querySelectorAll('[data-inventory-tab]').forEach((button) => button.addEventListener('click', () => { root.querySelectorAll('[data-inventory-tab]').forEach((x) => x.classList.toggle('active', x === button)); $('stock-panel').classList.toggle('d-none', button.dataset.inventoryTab !== 'stock'); $('expiry-panel').classList.toggle('d-none', button.dataset.inventoryTab !== 'expiry') }))
  await load()
}
