import { Modal } from 'bootstrap'
import Swal from 'sweetalert2'
import { ROLES } from '../utils/constants.js'
import { formatDateTime } from '../utils/formatters.js'
import { isRequired, isValidEmail, validateStrongPassword } from '../utils/validators.js'
import { actualizarPerfilUsuario, cambiarEstadoUsuario, cambiarPasswordUsuario, crearUsuario, enviarRecuperacion, getUsuarios } from '../services/usuariosService.js'

const escapeHtml = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;')
const roleLabels = { administrador: 'Administrador', rrhh: 'RRHH', monitora: 'Monitora' }
const metric = (label, id) => `<article class="metric-card"><span>${label}</span><strong id="${id}">0</strong></article>`
const roleOptions = (selected = '') => Object.entries(roleLabels).map(([value, label]) => `<option value="${value}" ${value === selected ? 'selected' : ''}>${label}</option>`).join('')
const modal = (id, title, body, submitLabel) => `<div class="modal fade" id="${id}" tabindex="-1" aria-labelledby="${id}-title" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><form id="${id}-form"><div class="modal-header"><h2 class="modal-title fs-5" id="${id}-title">${title}</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body">${body}</div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">${submitLabel}</button></div></form></div></div></div>`
const locationFields = (prefix) => `<div class="col-md-6 ${prefix}-location"><label class="form-label" for="${prefix}-site">Sede</label><select class="form-select" id="${prefix}-site" name="sedeId"><option value="">Sin asignar</option></select></div><div class="col-md-6 ${prefix}-location"><label class="form-label" for="${prefix}-shift">Turno</label><select class="form-select" id="${prefix}-shift" name="turnoId"><option value="">Sin asignar</option></select></div>`
const passwordFields = (prefix) => `<div class="col-md-6"><label class="form-label" for="${prefix}-password">Contraseña temporal</label><div class="input-group"><input class="form-control" id="${prefix}-password" name="password" type="password" autocomplete="new-password" required minlength="12"><button class="btn btn-outline-secondary password-toggle" type="button" data-target="${prefix}-password" aria-label="Mostrar contraseña">Mostrar</button></div></div><div class="col-md-6"><label class="form-label" for="${prefix}-confirm">Confirmar contraseña</label><input class="form-control" id="${prefix}-confirm" name="confirmPassword" type="password" autocomplete="new-password" required minlength="12"></div><div class="col-12"><small class="text-muted">Mínimo 12 caracteres, con mayúscula, minúscula, número y símbolo.</small></div>`

export const usuariosPage = ({ session }) => {
  if (session?.profile?.rol !== ROLES.ADMINISTRADOR) return '<section class="empty-state"><h3>Acceso restringido</h3><p>Tu perfil no tiene acceso a Usuarios.</p></section>'
  return `<section class="data-page users-page"><div class="page-heading data-heading"><div><p class="eyebrow">Administración</p><h2>Administración de usuarios</h2><p class="text-muted">Gestiona perfiles, roles, asignaciones y acceso de los usuarios autorizados.</p></div><div class="d-flex gap-2 users-heading-actions"><button class="btn btn-primary" id="users-new" type="button">Nuevo usuario</button><button class="btn btn-outline-primary" id="users-refresh" type="button">Actualizar</button></div></div>
    <div class="metrics-grid metrics-five">${metric('Total de usuarios', 'users-total')}${metric('Administradores', 'users-admins')}${metric('RRHH', 'users-hr')}${metric('Monitoras', 'users-monitors')}${metric('Usuarios inactivos', 'users-inactive')}</div>
    <section class="data-panel"><div id="users-status" class="loading-state" aria-live="polite">Consultando usuarios…</div><div id="users-results"></div></section>
    ${modal('user-create', 'Nuevo usuario', `<div class="row g-3"><div class="col-md-6"><label class="form-label" for="create-name">Nombre completo</label><input class="form-control" id="create-name" name="nombreCompleto" required></div><div class="col-md-6"><label class="form-label" for="create-email">Correo institucional</label><input class="form-control" id="create-email" name="correo" type="email" autocomplete="off" required></div><div class="col-md-6"><label class="form-label" for="create-role">Rol</label><select class="form-select" id="create-role" name="rol" required><option value="">Selecciona un rol</option>${roleOptions()}</select></div>${locationFields('create')}${passwordFields('create')}</div>`, 'Crear usuario')}
    ${modal('user-edit', 'Editar perfil', `<input type="hidden" name="userId"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="edit-name">Nombre completo</label><input class="form-control" id="edit-name" name="nombreCompleto" required></div><div class="col-md-6"><label class="form-label" for="edit-email">Correo</label><input class="form-control" id="edit-email" name="correo" type="email" readonly></div><div class="col-md-6"><label class="form-label" for="edit-role">Rol</label><select class="form-select" id="edit-role" name="rol" required>${roleOptions()}</select></div>${locationFields('edit')}</div>`, 'Guardar cambios')}
    ${modal('user-password', 'Cambiar contraseña', `<input type="hidden" name="userId"><p>Usuario: <strong id="password-user-name"></strong></p><div class="alert alert-warning">Esta acción reemplazará la contraseña actual del usuario.</div><div class="row g-3">${passwordFields('change')}</div>`, 'Cambiar contraseña')}
  </section>`
}

export const initUsuariosPage = async ({ session }) => {
  if (session?.profile?.rol !== ROLES.ADMINISTRADOR) return
  const root = document.querySelector('.users-page'); if (!root) return
  const state = { usuarios: [], sedes: [], turnos: [], loading: false }
  const $ = (id) => root.querySelector(`#${id}`)
  const modals = { create: Modal.getOrCreateInstance($('user-create')), edit: Modal.getOrCreateInstance($('user-edit')), password: Modal.getOrCreateInstance($('user-password')) }
  const errorMessage = (error, fallback) => ({ email_exists: 'Ya existe un usuario con ese correo.', weak_password: 'La contraseña no cumple los requisitos de seguridad.', user_not_found: 'El usuario no existe.', forbidden: 'No tienes autorización para realizar esta acción.', session_expired: 'Tu sesión venció. Inicia sesión nuevamente.', last_admin: error.message, self_deactivation: error.message, network_error: 'No fue posible conectar con el servicio.' }[error?.code] || fallback)
  const notifyError = (error, fallback) => Swal.fire({ icon: 'error', title: fallback, text: errorMessage(error, fallback) })
  const setBusy = (form, busy, label) => { const button = form.querySelector('[type="submit"]'); button.disabled = busy; if (!button.dataset.label) button.dataset.label = button.textContent; button.textContent = busy ? label : button.dataset.label }
  const options = (items, selected) => items.filter((item) => item.activa ?? item.activo).map((item) => `<option value="${item.id}" ${String(item.id) === String(selected) ? 'selected' : ''}>${escapeHtml(item.nombre)}</option>`).join('')
  const fillLocations = (prefix, site = '', shift = '') => { $(`${prefix}-site`).innerHTML = `<option value="">Sin asignar</option>${options(state.sedes, site)}`; $(`${prefix}-shift`).innerHTML = `<option value="">Sin asignar</option>${options(state.turnos, shift)}` }
  const toggleLocations = (prefix) => { const required = $(`${prefix}-role`).value === 'monitora'; $(`${prefix}-site`).required = required; $(`${prefix}-shift`).required = required }
  const validProfile = (data) => isRequired(data.nombreCompleto) && roleLabels[data.rol] && (data.rol !== 'monitora' || (data.sedeId && data.turnoId))
  const validPasswordForm = (data) => data.password === data.confirmPassword && validateStrongPassword(data.password)

  const render = () => {
    const users = state.usuarios
    $('users-total').textContent = users.length; $('users-admins').textContent = users.filter((item) => item.rol === 'administrador').length; $('users-hr').textContent = users.filter((item) => item.rol === 'rrhh').length; $('users-monitors').textContent = users.filter((item) => item.rol === 'monitora').length; $('users-inactive').textContent = users.filter((item) => !item.activo).length
    $('users-status').textContent = users.length ? `${users.length} usuario(s) registrado(s).` : 'No hay usuarios registrados.'
    const actions = (item) => `<div class="d-flex flex-wrap gap-1"><button class="btn btn-sm btn-outline-primary" data-user-action="edit" data-user-id="${item.user_id}">Editar perfil</button><button class="btn btn-sm btn-outline-secondary" data-user-action="password" data-user-id="${item.user_id}">Cambiar contraseña</button><button class="btn btn-sm ${item.activo ? 'btn-outline-danger' : 'btn-outline-success'}" data-user-action="active" data-user-id="${item.user_id}">${item.activo ? 'Desactivar' : 'Activar'}</button><button class="btn btn-sm btn-outline-secondary" data-user-action="recovery" data-user-id="${item.user_id}">Enviar recuperación</button></div>`
    $('users-results').innerHTML = users.length ? `<div class="desktop-table"><table class="table align-middle"><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th><th>Sede</th><th>Turno</th><th>Estado</th><th>Último acceso</th><th>Acciones</th></tr></thead><tbody>${users.map((item) => `<tr><td>${escapeHtml(item.nombre_completo)}</td><td>${escapeHtml(item.correo)}</td><td>${roleLabels[item.rol] || escapeHtml(item.rol)}</td><td>${escapeHtml(item.sede || '—')}</td><td>${escapeHtml(item.turno || '—')}</td><td><span class="status-badge ${item.activo ? 'status-normal' : 'status-agotado'}">${item.activo ? 'Activo' : 'Inactivo'}</span></td><td>${formatDateTime(item.ultimo_acceso)}</td><td>${actions(item)}</td></tr>`).join('')}</tbody></table></div><div class="mobile-cards">${users.map((item) => `<article class="data-card"><h4>${escapeHtml(item.nombre_completo)}</h4><p>${escapeHtml(item.correo)}</p><dl><div><dt>Rol</dt><dd>${roleLabels[item.rol]}</dd></div><div><dt>Asignación</dt><dd>${escapeHtml([item.sede, item.turno].filter(Boolean).join(' · ') || '—')}</dd></div><div><dt>Último acceso</dt><dd>${formatDateTime(item.ultimo_acceso)}</dd></div><div><dt>Estado</dt><dd>${item.activo ? 'Activo' : 'Inactivo'}</dd></div></dl>${actions(item)}</article>`).join('')}</div>` : ''
  }
  const load = async () => {
    if (state.loading) return; state.loading = true; $('users-status').textContent = 'Consultando usuarios…'; $('users-refresh').disabled = true
    try { const data = await getUsuarios(); state.usuarios = data.usuarios; state.sedes = data.sedes; state.turnos = data.turnos; fillLocations('create'); fillLocations('edit'); render() } catch (error) { $('users-status').textContent = 'No fue posible consultar los usuarios.'; notifyError(error, 'No fue posible consultar los usuarios.') } finally { state.loading = false; $('users-refresh').disabled = false }
  }

  $('users-new').addEventListener('click', () => { $('user-create-form').reset(); fillLocations('create'); toggleLocations('create'); modals.create.show() })
  $('users-refresh').addEventListener('click', load)
  ;['create', 'edit'].forEach((prefix) => $(`${prefix}-role`).addEventListener('change', () => toggleLocations(prefix)))
  root.querySelectorAll('.password-toggle').forEach((button) => button.addEventListener('click', () => { const input = $(button.dataset.target); const show = input.type === 'password'; input.type = show ? 'text' : 'password'; button.textContent = show ? 'Ocultar' : 'Mostrar'; button.setAttribute('aria-label', `${show ? 'Ocultar' : 'Mostrar'} contraseña`) }))
  root.querySelectorAll('.modal').forEach((element) => element.addEventListener('hidden.bs.modal', () => { const form = element.querySelector('form'); form?.reset(); form?.querySelectorAll('input[type="password"]').forEach((input) => { input.value = ''; input.type = 'password' }); form?.querySelectorAll('.password-toggle').forEach((button) => { button.textContent = 'Mostrar' }) }))

  $('user-create-form').addEventListener('submit', async (event) => {
    event.preventDefault(); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form))
    if (!validProfile(data) || !isValidEmail(data.correo)) return Swal.fire({ icon: 'warning', title: 'Revisa los datos', text: 'Completa correctamente los campos obligatorios.' })
    if (!validPasswordForm(data)) return Swal.fire({ icon: 'warning', title: 'Contraseña no válida', text: data.password !== data.confirmPassword ? 'Las contraseñas no coinciden.' : 'La contraseña no cumple todos los requisitos.' })
    setBusy(form, true, 'Creando…')
    try { await crearUsuario({ nombreCompleto: data.nombreCompleto, correo: data.correo, rol: data.rol, sedeId: data.sedeId || null, turnoId: data.turnoId || null, passwordTemporal: data.password }); form.reset(); modals.create.hide(); await load(); Swal.fire({ icon: 'success', title: 'Usuario creado correctamente', text: 'Entrega la contraseña temporal de forma privada.' }) } catch (error) { notifyError(error, 'No fue posible crear el usuario.') } finally { form.querySelectorAll('input[type="password"]').forEach((input) => { input.value = '' }); setBusy(form, false) }
  })
  $('user-edit-form').addEventListener('submit', async (event) => {
    event.preventDefault(); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); if (!validProfile(data)) return Swal.fire({ icon: 'warning', title: 'Revisa los datos', text: 'Completa correctamente los campos obligatorios.' }); setBusy(form, true, 'Guardando…')
    try { await actualizarPerfilUsuario({ userId: data.userId, nombreCompleto: data.nombreCompleto, rol: data.rol, sedeId: data.sedeId || null, turnoId: data.turnoId || null }); modals.edit.hide(); await load(); Swal.fire({ icon: 'success', title: 'Perfil actualizado' }) } catch (error) { notifyError(error, 'No fue posible actualizar el perfil.') } finally { setBusy(form, false) }
  })
  $('user-password-form').addEventListener('submit', async (event) => {
    event.preventDefault(); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); if (!validPasswordForm(data)) return Swal.fire({ icon: 'warning', title: 'Contraseña no válida', text: data.password !== data.confirmPassword ? 'Las contraseñas no coinciden.' : 'La contraseña no cumple todos los requisitos.' }); const confirmation = await Swal.fire({ icon: 'warning', title: 'Confirmar cambio', text: 'Esta acción reemplazará la contraseña actual del usuario.', showCancelButton: true, confirmButtonText: 'Cambiar contraseña', cancelButtonText: 'Cancelar' }); if (!confirmation.isConfirmed) return; setBusy(form, true, 'Cambiando…')
    try { await cambiarPasswordUsuario(data.userId, data.password); form.reset(); modals.password.hide(); Swal.fire({ icon: 'success', title: 'Contraseña actualizada' }) } catch (error) { notifyError(error, 'No fue posible cambiar la contraseña.') } finally { form.querySelectorAll('input[type="password"]').forEach((input) => { input.value = '' }); setBusy(form, false) }
  })
  $('users-results').addEventListener('click', async (event) => {
    const button = event.target.closest('[data-user-action]'); if (!button) return; const item = state.usuarios.find((user) => user.user_id === button.dataset.userId); if (!item) return
    if (button.dataset.userAction === 'edit') { const form = $('user-edit-form'); const site = state.sedes.find((entry) => entry.nombre === item.sede)?.id ?? ''; const shift = state.turnos.find((entry) => entry.nombre === item.turno)?.id ?? ''; form.elements.userId.value = item.user_id; form.elements.nombreCompleto.value = item.nombre_completo; form.elements.correo.value = item.correo; form.elements.rol.value = item.rol; fillLocations('edit', site, shift); toggleLocations('edit'); modals.edit.show(); return }
    if (button.dataset.userAction === 'password') { const form = $('user-password-form'); form.reset(); form.elements.userId.value = item.user_id; $('password-user-name').textContent = item.nombre_completo; modals.password.show(); return }
    if (button.dataset.userAction === 'active') { const next = !item.activo; if (!next) { const confirmation = await Swal.fire({ icon: 'warning', title: 'Desactivar usuario', text: `¿Deseas desactivar a ${item.nombre_completo}?`, showCancelButton: true, confirmButtonText: 'Desactivar', cancelButtonText: 'Cancelar' }); if (!confirmation.isConfirmed) return } button.disabled = true; try { await cambiarEstadoUsuario(item.user_id, next); await load(); Swal.fire({ icon: 'success', title: next ? 'Usuario activado' : 'Usuario desactivado' }) } catch (error) { notifyError(error, 'No fue posible cambiar el estado del usuario.'); button.disabled = false } return }
    const confirmation = await Swal.fire({ icon: 'question', title: 'Enviar recuperación', text: `Se procesará una solicitud para ${item.correo}.`, showCancelButton: true, confirmButtonText: 'Procesar', cancelButtonText: 'Cancelar' }); if (!confirmation.isConfirmed) return; button.disabled = true
    try { await enviarRecuperacion(item.correo); Swal.fire({ icon: 'success', title: 'Se procesó la solicitud de recuperación.' }) } catch (error) { notifyError(error, 'No fue posible procesar la recuperación.') } finally { button.disabled = false }
  })
  toggleLocations('create'); await load()
}
