-- Generado por scripts/preparar-inventario.mjs. Revisar pendientes antes de ejecutar.
-- No multiplica existencias por contenido_por_presentacion y no crea movimientos.
begin;

do $$ declare r record; begin
+  for r in select v.codigo, v.nombre_nuevo, p.nombre nombre_existente from (values
    ('31A', 'ACERCA - 10 TABLETA'),
    ('8A', 'ACETAMINOFEM GENFAR 500 MG - 100 TABLETA'),
    ('22A', 'AERO OM VAINILLA 40MG - 1 COMPRIMIDO MASTICABLE'),
    ('9A', 'ALFER ERI 0.5% 5ML SOLUCION OFTALMICA'),
    ('38A', 'ASPIRINA FORTE 650MG - 1 TABLETA'),
    ('3A', 'CARDIOASPIRINA 81MG'),
    ('33A', 'CLORFENIRAMINA ECOMED 4MG - 10 TABLETA'),
    ('57A', 'CLORFENIRAMINA SELECT AMPOLLA'),
    ('12A', 'COFAL REGULAR 120G CREMA'),
    ('47A', 'COMPLEJO B VIAL'),
    ('19A', 'DESKETOPROFENO 25 MG TABLETA'),
    ('48A', 'DESKETOPROFENO AMPOLLA'),
    ('59A', 'DESLORATADINA 5MG - 10 TABLETA'),
    ('49A', 'DEXAMETASONA AMPOLLA'),
    ('50A', 'DICLOFENACO 50 mg TABLETA'),
    ('MED-AUTO-016', 'DICLOFENACO 75 MG/3 ML AMPOLLA'),
    ('11A', 'DICLOLEV 0.01% 20G GEL'),
    ('39A', 'DICLOLEV 75MG/3ML - 2 SOLUCION INYECTABLE IM (KIT)'),
    ('MED-AUTO-019', 'DIPIRONA 1G/2 ML AMPOLLA'),
    ('7A', 'DOLO KALORUB 180ML AERO'),
    ('21A', 'DOLONEUROBION - 1 TABLETA'),
    ('36A', 'DORIVAL 200MG - 36 CAPSULAS GEL'),
    ('MED-AUTO-023', 'ENALAPRIL 20 mg tableta'),
    ('32A', 'FRIORUB 180ML AERO'),
    ('40A', 'GLICERINA GOTERO'),
    ('MED-AUTO-026', 'GLORANTA SABORES SURTIDOS 100 CARAMELOS (25 SOBRES X 4)'),
    ('42A', 'HIDROXONA MIX DE ELECTROLITOS MORA- 30 SOBRES POLVO'),
    ('MED-AUTO-028', 'HIDROXONA MIX DE ELECTROLITOS NARANJA - 30 SOBRES POLVO'),
    ('44A', 'HIDROXONA MIX DE ELECTROLITOS NEUTRO - 30 SOBRES POLVO'),
    ('45A', 'HIDROXONA MIX DE ELECTROLITOS SABORES- 30 SOBRES POLVO'),
    ('46A', 'HIDROXONA MIX DE ELECTROLITOS UVA - 30 SOBRES POLVO'),
    ('43A', 'HIPOPRES GOTERO'),
    ('34A', 'HISTAPRIM 10MG/1 ML AMPOLLA'),
    ('MED-AUTO-034', 'HISTAPRIN 4MG/32MG - 10 COMPRIMIDOS'),
    ('23A', 'I.R.S. - 1 TABLETA'),
    ('55A', 'IBATROPIUM VIAL 20ML VIJOSA'),
    ('6A', 'IBUPROFENO GENFAR 600MG - 50 TABLETA'),
    ('51A', 'LANSOPRAZOL CAJA - 100 UNIDADES'),
    ('30A', 'LEVEN (NEUROTROPAS) 25000 - 1 SOLUCION INYECTABLE (2+1)'),
    ('16A', 'LOMZOL 400MG - 24 TABLETA'),
    ('37A', 'LORATADINA FAMANDINA 10MG - 1 TABLETA'),
    ('52A', 'METOCARBAMOL 100MG/5ML AMPOLLA'),
    ('28A', 'METOCARBAMOL ECOMED 500MG - 10 TABLETAS'),
    ('MED-AUTO-044', 'METRONIDAZOL 500 MG TABLETAS'),
    ('58A', 'NAUSEOL 50 MG/1ML AMPOLLA'),
    ('29A', 'NAUSEOL 50MG - 1 COMPRIMIDO'),
    ('20A', 'NAZIL OFTENO 0.1% 15ML SOLUCION OFTALMICA'),
    ('35A', 'NEO MELUBRINA 500MG - 4 TABLETA'),
    ('1A', 'NEOBAL 30G CREMA'),
    ('4A', 'NEOBOL 150 (30ML)'),
    ('10A', 'NEUOMONIL 1 SOLUCION INYECTABLE'),
    ('60A', 'OMEPRAZOL'),
    ('18A', 'OTIK 10ML SOLUCION OTICA'),
    ('24A', 'PASINERVA - 5 CAPSULAS'),
    ('15A', 'REFRESH TEARS 0.5% 15ML SOLUCION OFTALMICA'),
    ('17A', 'REPANTHENE REGENERADORA 5% 30G CREMA'),
    ('26A', 'RUIGEL PLUS BT MENA 360ML ANTIACIDO'),
    ('2A', 'SAL ANDREWS 50 SOBRES POLVO'),
    ('53A', 'SALBUTAMO SELECTPHARMA'),
    ('54A', 'SERTAL COMPUESTO / KLORPROSIN SOL INYECTABLE'),
    ('27A', 'SERTAL COMPUESTO 125MG/10MG - 1 COMPRIMIDO'),
    ('13A', 'SULFADIAZINA DE PLATA GENFAR 1% 15G CREMA'),
    ('5A', 'TABCIN GRIPE Y TOS - 60 TABLETAS'),
    ('14A', 'TRIPROFEN (IBUPROFENO) 800MG - 10 TABLETA'),
    ('25A', 'VITAFLENACO - 1 CAPSULA GEL'),
    ('56A', 'VITAMINA K / BONADINA AMPOLLA'),
    ('MED-AUTO-067', 'BEPANTHENE PROTECTOR'),
    ('MED-AUTO-068', 'METOCLOPRAMIDA AMPOLLA'),
    ('MED-AUTO-069', 'LOPERAMIDA'),
    ('MED-AUTO-070', 'ENZIMAS'),
    ('MED-AUTO-071', 'ALKA ZELTER'),
    ('MED-AUTO-072', 'VASELINA'),
    ('MED-AUTO-073', 'KURA KURA'),
    ('MED-AUTO-074', 'TROPIUM'),
    ('MED-AUTO-075', 'BUDENA'),
    ('MED-AUTO-076', 'SUEROS'),
    ('1B', 'AGUA OXIGENADA GALÓN'),
    ('2B', 'AGUJAS #18'),
    ('3B', 'AGUJAS #23'),
    ('4B', 'ALCOHOL ETILICO'),
    ('INS-AUTO-005', 'AGUA ESTERIL'),
    ('5B', 'ALGODÓN ROLLO'),
    ('6B', 'AMPOLLAS PARA ESTERILIZAR EQUIPO 5cc'),
    ('7B', 'ANGIOCATH #20'),
    ('INS-AUTO-009', 'ANGIOCATH #22'),
    ('INS-AUTO-010', 'ANGIOCATH #24'),
    ('INS-AUTO-011', 'BAJA LENGUAS LIMPIAS'),
    ('8B', 'BUDENA BUDEGEN 10ML'),
    ('INS-AUTO-013', 'CABESTRILLO ADULTO'),
    ('9B', 'CANULAS BINASALES'),
    ('10B', 'CLORHEXIDINA GALON'),
    ('11B', 'CURITAS CAJA'),
    ('INS-AUTO-017', 'ESPARADRAPO 3 PULGADAS'),
    ('INS-AUTO-018', 'ESPARADRAPO 1PULGADAS'),
    ('12B', 'FERULA DE DEDO GRANDE'),
    ('INS-AUTO-020', 'FERULA DE DEDO PEQUEÑO'),
    ('INS-AUTO-021', 'GASAS VASELINADAS'),
    ('INS-AUTO-022', 'GUANTES ESTERILES 6.5'),
    ('13B', 'HILO DE SUTURA NYLON 2-0'),
    ('INS-AUTO-024', 'HILO DE SUTURA NYLON 3-0'),
    ('INS-AUTO-025', 'HILO DE SUTURA VICRIL 2-0'),
    ('INS-AUTO-026', 'HILO DE SUTURA SEDA 4-0'),
    ('14B', 'HISOPOS - 100 UNIDADES'),
    ('INS-AUTO-028', 'HOJAS DE BISTURY'),
    ('15B', 'JERINGA DE 1 CC'),
    ('16B', 'JERINGA POMEROY'),
    ('INS-AUTO-031', 'JERINGAS DE 10cc CAJA - 100 UNIDADES'),
    ('INS-AUTO-032', 'JERINGAS DE 3cc CAJA - 100 UNIDADES'),
    ('17B', 'JERINGAS DE 5cc CAJA - 100'),
    ('18B', 'LANCETAS PARA GLUCÓMETRO'),
    ('19B', 'LIDOCAINA 2% FRASCO'),
    ('20B', 'MASCARILLA PARA NEBULIZAR'),
    ('21B', 'MASCARILLAS CON RESERVORIO'),
    ('22B', 'MICROPORE 1 PULGADA'),
    ('23B', 'MICROPORE 3 PULGADAS'),
    ('24B', 'PIEZA DE GASA'),
    ('25B', 'SOL. HARTMAN 500ML'),
    ('26B', 'SOL. SN 500ML'),
    ('INS-AUTO-043', 'SOL. SSN 100ML'),
    ('27B', 'STOPPER'),
    ('28B', 'TIJERA PARA CORTAR PUNTOS DE SUTURA 4.5'),
    ('29B', 'TIRAS DE GLUCÓMETRO NIPRO PREMIER'),
    ('30B', 'TIRAS DE GLUCÓMETRO ON CALL'),
    ('31B', 'VENDAS DE GASA DE 2 PULGADAS'),
    ('32B', 'VENDAS ELASTICAS 2 PULGADAS'),
    ('33B', 'VENDAS ELASTICAS 3 PULGADAS'),
    ('34B', 'VENDAS ELASTICAS 4 PULGADAS'),
    ('35B', 'VENOSETH')
  ) v(codigo, nombre_nuevo) join public.productos p on p.codigo = v.codigo where p.nombre is distinct from v.nombre_nuevo
+  loop raise warning 'Código % ya existe con nombre distinto: existente=%, propuesto=%', r.codigo, r.nombre_existente, r.nombre_nuevo; end loop;
end $$;

insert into public.productos (codigo, nombre, categoria, presentacion, unidad_medida, estado, es_consumible, contenido_por_presentacion, unidad_dispensacion, permite_registro_sin_descuento)
values
  ('31A', 'ACERCA - 10 TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 10, 'tableta', false),
  ('8A', 'ACETAMINOFEM GENFAR 500 MG - 100 TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 100, 'tableta', false),
  ('22A', 'AERO OM VAINILLA 40MG - 1 COMPRIMIDO MASTICABLE', 'medicamento'::public.categoria_producto, 'comprimido', 'comprimido', 'activo'::public.estado_producto, true, 1, 'comprimido', false),
  ('9A', 'ALFER ERI 0.5% 5ML SOLUCION OFTALMICA', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('38A', 'ASPIRINA FORTE 650MG - 1 TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 1, 'tableta', false),
  ('3A', 'CARDIOASPIRINA 81MG', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('33A', 'CLORFENIRAMINA ECOMED 4MG - 10 TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 10, 'tableta', false),
  ('57A', 'CLORFENIRAMINA SELECT AMPOLLA', 'medicamento'::public.categoria_producto, 'ampolla', 'ampolla', 'activo'::public.estado_producto, true, 1, 'ampolla', false),
  ('12A', 'COFAL REGULAR 120G CREMA', 'medicamento'::public.categoria_producto, 'crema', 'crema', 'activo'::public.estado_producto, true, 1, 'crema', false),
  ('47A', 'COMPLEJO B VIAL', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('19A', 'DESKETOPROFENO 25 MG TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 1, 'tableta', false),
  ('48A', 'DESKETOPROFENO AMPOLLA', 'medicamento'::public.categoria_producto, 'ampolla', 'ampolla', 'activo'::public.estado_producto, true, 1, 'ampolla', false),
  ('59A', 'DESLORATADINA 5MG - 10 TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 10, 'tableta', false),
  ('49A', 'DEXAMETASONA AMPOLLA', 'medicamento'::public.categoria_producto, 'ampolla', 'ampolla', 'activo'::public.estado_producto, true, 1, 'ampolla', false),
  ('50A', 'DICLOFENACO 50 mg TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 1, 'tableta', false),
  ('MED-AUTO-016', 'DICLOFENACO 75 MG/3 ML AMPOLLA', 'medicamento'::public.categoria_producto, 'ampolla', 'ampolla', 'activo'::public.estado_producto, true, 1, 'ampolla', false),
  ('11A', 'DICLOLEV 0.01% 20G GEL', 'medicamento'::public.categoria_producto, 'gel', 'gel', 'activo'::public.estado_producto, true, 1, 'gel', false),
  ('39A', 'DICLOLEV 75MG/3ML - 2 SOLUCION INYECTABLE IM (KIT)', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('MED-AUTO-019', 'DIPIRONA 1G/2 ML AMPOLLA', 'medicamento'::public.categoria_producto, 'ampolla', 'ampolla', 'activo'::public.estado_producto, true, 1, 'ampolla', false),
  ('7A', 'DOLO KALORUB 180ML AERO', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('21A', 'DOLONEUROBION - 1 TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 1, 'tableta', false),
  ('36A', 'DORIVAL 200MG - 36 CAPSULAS GEL', 'medicamento'::public.categoria_producto, 'cápsula', 'cápsula', 'activo'::public.estado_producto, true, 36, 'capsula', false),
  ('MED-AUTO-023', 'ENALAPRIL 20 mg tableta', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 1, 'tableta', false),
  ('32A', 'FRIORUB 180ML AERO', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('40A', 'GLICERINA GOTERO', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('MED-AUTO-026', 'GLORANTA SABORES SURTIDOS 100 CARAMELOS (25 SOBRES X 4)', 'medicamento'::public.categoria_producto, 'sobre', 'sobre', 'activo'::public.estado_producto, true, 25, 'sobre', false),
  ('42A', 'HIDROXONA MIX DE ELECTROLITOS MORA- 30 SOBRES POLVO', 'medicamento'::public.categoria_producto, 'sobre', 'sobre', 'activo'::public.estado_producto, true, 30, 'sobre', false),
  ('MED-AUTO-028', 'HIDROXONA MIX DE ELECTROLITOS NARANJA - 30 SOBRES POLVO', 'medicamento'::public.categoria_producto, 'sobre', 'sobre', 'activo'::public.estado_producto, true, 30, 'sobre', false),
  ('44A', 'HIDROXONA MIX DE ELECTROLITOS NEUTRO - 30 SOBRES POLVO', 'medicamento'::public.categoria_producto, 'sobre', 'sobre', 'activo'::public.estado_producto, true, 30, 'sobre', false),
  ('45A', 'HIDROXONA MIX DE ELECTROLITOS SABORES- 30 SOBRES POLVO', 'medicamento'::public.categoria_producto, 'sobre', 'sobre', 'activo'::public.estado_producto, true, 30, 'sobre', false),
  ('46A', 'HIDROXONA MIX DE ELECTROLITOS UVA - 30 SOBRES POLVO', 'medicamento'::public.categoria_producto, 'sobre', 'sobre', 'activo'::public.estado_producto, true, 30, 'sobre', false),
  ('43A', 'HIPOPRES GOTERO', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('34A', 'HISTAPRIM 10MG/1 ML AMPOLLA', 'medicamento'::public.categoria_producto, 'ampolla', 'ampolla', 'activo'::public.estado_producto, true, 1, 'ampolla', false),
  ('MED-AUTO-034', 'HISTAPRIN 4MG/32MG - 10 COMPRIMIDOS', 'medicamento'::public.categoria_producto, 'comprimido', 'comprimido', 'activo'::public.estado_producto, true, 10, 'comprimido', false),
  ('23A', 'I.R.S. - 1 TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 1, 'tableta', false),
  ('55A', 'IBATROPIUM VIAL 20ML VIJOSA', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('6A', 'IBUPROFENO GENFAR 600MG - 50 TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 50, 'tableta', false),
  ('51A', 'LANSOPRAZOL CAJA - 100 UNIDADES', 'medicamento'::public.categoria_producto, 'caja', 'caja', 'activo'::public.estado_producto, true, 100, 'unidad', false),
  ('30A', 'LEVEN (NEUROTROPAS) 25000 - 1 SOLUCION INYECTABLE (2+1)', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('16A', 'LOMZOL 400MG - 24 TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 24, 'tableta', false),
  ('37A', 'LORATADINA FAMANDINA 10MG - 1 TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 1, 'tableta', false),
  ('52A', 'METOCARBAMOL 100MG/5ML AMPOLLA', 'medicamento'::public.categoria_producto, 'ampolla', 'ampolla', 'activo'::public.estado_producto, true, 1, 'ampolla', false),
  ('28A', 'METOCARBAMOL ECOMED 500MG - 10 TABLETAS', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 10, 'tableta', false),
  ('MED-AUTO-044', 'METRONIDAZOL 500 MG TABLETAS', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 1, 'tableta', false),
  ('58A', 'NAUSEOL 50 MG/1ML AMPOLLA', 'medicamento'::public.categoria_producto, 'ampolla', 'ampolla', 'activo'::public.estado_producto, true, 1, 'ampolla', false),
  ('29A', 'NAUSEOL 50MG - 1 COMPRIMIDO', 'medicamento'::public.categoria_producto, 'comprimido', 'comprimido', 'activo'::public.estado_producto, true, 1, 'comprimido', false),
  ('20A', 'NAZIL OFTENO 0.1% 15ML SOLUCION OFTALMICA', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('35A', 'NEO MELUBRINA 500MG - 4 TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 4, 'tableta', false),
  ('1A', 'NEOBAL 30G CREMA', 'medicamento'::public.categoria_producto, 'crema', 'crema', 'activo'::public.estado_producto, true, 1, 'crema', false),
  ('4A', 'NEOBOL 150 (30ML)', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('10A', 'NEUOMONIL 1 SOLUCION INYECTABLE', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('60A', 'OMEPRAZOL', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('18A', 'OTIK 10ML SOLUCION OTICA', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('24A', 'PASINERVA - 5 CAPSULAS', 'medicamento'::public.categoria_producto, 'cápsula', 'cápsula', 'activo'::public.estado_producto, true, 5, 'capsula', false),
  ('15A', 'REFRESH TEARS 0.5% 15ML SOLUCION OFTALMICA', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('17A', 'REPANTHENE REGENERADORA 5% 30G CREMA', 'medicamento'::public.categoria_producto, 'crema', 'crema', 'activo'::public.estado_producto, true, 1, 'crema', false),
  ('26A', 'RUIGEL PLUS BT MENA 360ML ANTIACIDO', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('2A', 'SAL ANDREWS 50 SOBRES POLVO', 'medicamento'::public.categoria_producto, 'sobre', 'sobre', 'activo'::public.estado_producto, true, 50, 'sobre', false),
  ('53A', 'SALBUTAMO SELECTPHARMA', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('54A', 'SERTAL COMPUESTO / KLORPROSIN SOL INYECTABLE', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('27A', 'SERTAL COMPUESTO 125MG/10MG - 1 COMPRIMIDO', 'medicamento'::public.categoria_producto, 'comprimido', 'comprimido', 'activo'::public.estado_producto, true, 1, 'comprimido', false),
  ('13A', 'SULFADIAZINA DE PLATA GENFAR 1% 15G CREMA', 'medicamento'::public.categoria_producto, 'crema', 'crema', 'activo'::public.estado_producto, true, 1, 'crema', false),
  ('5A', 'TABCIN GRIPE Y TOS - 60 TABLETAS', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 60, 'tableta', false),
  ('14A', 'TRIPROFEN (IBUPROFENO) 800MG - 10 TABLETA', 'medicamento'::public.categoria_producto, 'tableta', 'tableta', 'activo'::public.estado_producto, true, 10, 'tableta', false),
  ('25A', 'VITAFLENACO - 1 CAPSULA GEL', 'medicamento'::public.categoria_producto, 'cápsula', 'cápsula', 'activo'::public.estado_producto, true, 1, 'capsula', false),
  ('56A', 'VITAMINA K / BONADINA AMPOLLA', 'medicamento'::public.categoria_producto, 'ampolla', 'ampolla', 'activo'::public.estado_producto, true, 1, 'ampolla', false),
  ('MED-AUTO-067', 'BEPANTHENE PROTECTOR', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('MED-AUTO-068', 'METOCLOPRAMIDA AMPOLLA', 'medicamento'::public.categoria_producto, 'ampolla', 'ampolla', 'activo'::public.estado_producto, true, 1, 'ampolla', false),
  ('MED-AUTO-069', 'LOPERAMIDA', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('MED-AUTO-070', 'ENZIMAS', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('MED-AUTO-071', 'ALKA ZELTER', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('MED-AUTO-072', 'VASELINA', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('MED-AUTO-073', 'KURA KURA', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('MED-AUTO-074', 'TROPIUM', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('MED-AUTO-075', 'BUDENA', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('MED-AUTO-076', 'SUEROS', 'medicamento'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('1B', 'AGUA OXIGENADA GALÓN', 'insumo'::public.categoria_producto, 'galón', 'galón', 'activo'::public.estado_producto, true, 1, 'galón', false),
  ('2B', 'AGUJAS #18', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('3B', 'AGUJAS #23', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('4B', 'ALCOHOL ETILICO', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('INS-AUTO-005', 'AGUA ESTERIL', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('5B', 'ALGODÓN ROLLO', 'insumo'::public.categoria_producto, 'rollo', 'rollo', 'activo'::public.estado_producto, true, 1, 'rollo', false),
  ('6B', 'AMPOLLAS PARA ESTERILIZAR EQUIPO 5cc', 'insumo'::public.categoria_producto, 'ampolla', 'ampolla', 'activo'::public.estado_producto, true, 1, 'ampolla', false),
  ('7B', 'ANGIOCATH #20', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('INS-AUTO-009', 'ANGIOCATH #22', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('INS-AUTO-010', 'ANGIOCATH #24', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('INS-AUTO-011', 'BAJA LENGUAS LIMPIAS', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('8B', 'BUDENA BUDEGEN 10ML', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('INS-AUTO-013', 'CABESTRILLO ADULTO', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, false, 1, 'unidad', true),
  ('9B', 'CANULAS BINASALES', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('10B', 'CLORHEXIDINA GALON', 'insumo'::public.categoria_producto, 'galón', 'galón', 'activo'::public.estado_producto, true, 1, 'galón', false),
  ('11B', 'CURITAS CAJA', 'insumo'::public.categoria_producto, 'caja', 'caja', 'activo'::public.estado_producto, true, 1, 'caja', false),
  ('INS-AUTO-017', 'ESPARADRAPO 3 PULGADAS', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('INS-AUTO-018', 'ESPARADRAPO 1PULGADAS', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('12B', 'FERULA DE DEDO GRANDE', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, false, 1, 'unidad', true),
  ('INS-AUTO-020', 'FERULA DE DEDO PEQUEÑO', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, false, 1, 'unidad', true),
  ('INS-AUTO-021', 'GASAS VASELINADAS', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('INS-AUTO-022', 'GUANTES ESTERILES 6.5', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('13B', 'HILO DE SUTURA NYLON 2-0', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('INS-AUTO-024', 'HILO DE SUTURA NYLON 3-0', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('INS-AUTO-025', 'HILO DE SUTURA VICRIL 2-0', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('INS-AUTO-026', 'HILO DE SUTURA SEDA 4-0', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('14B', 'HISOPOS - 100 UNIDADES', 'insumo'::public.categoria_producto, 'unidad', 'unidad', 'activo'::public.estado_producto, true, 100, 'unidad', false),
  ('INS-AUTO-028', 'HOJAS DE BISTURY', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('15B', 'JERINGA DE 1 CC', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('16B', 'JERINGA POMEROY', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('INS-AUTO-031', 'JERINGAS DE 10cc CAJA - 100 UNIDADES', 'insumo'::public.categoria_producto, 'caja', 'caja', 'activo'::public.estado_producto, true, 100, 'unidad', false),
  ('INS-AUTO-032', 'JERINGAS DE 3cc CAJA - 100 UNIDADES', 'insumo'::public.categoria_producto, 'caja', 'caja', 'activo'::public.estado_producto, true, 100, 'unidad', false),
  ('17B', 'JERINGAS DE 5cc CAJA - 100', 'insumo'::public.categoria_producto, 'caja', 'caja', 'activo'::public.estado_producto, true, 1, 'caja', false),
  ('18B', 'LANCETAS PARA GLUCÓMETRO', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('19B', 'LIDOCAINA 2% FRASCO', 'insumo'::public.categoria_producto, 'frasco', 'frasco', 'activo'::public.estado_producto, true, 1, 'frasco', false),
  ('20B', 'MASCARILLA PARA NEBULIZAR', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('21B', 'MASCARILLAS CON RESERVORIO', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('22B', 'MICROPORE 1 PULGADA', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('23B', 'MICROPORE 3 PULGADAS', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('24B', 'PIEZA DE GASA', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('25B', 'SOL. HARTMAN 500ML', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('26B', 'SOL. SN 500ML', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('INS-AUTO-043', 'SOL. SSN 100ML', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('27B', 'STOPPER', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('28B', 'TIJERA PARA CORTAR PUNTOS DE SUTURA 4.5', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, false, 1, 'unidad', true),
  ('29B', 'TIRAS DE GLUCÓMETRO NIPRO PREMIER', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('30B', 'TIRAS DE GLUCÓMETRO ON CALL', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('31B', 'VENDAS DE GASA DE 2 PULGADAS', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('32B', 'VENDAS ELASTICAS 2 PULGADAS', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('33B', 'VENDAS ELASTICAS 3 PULGADAS', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('34B', 'VENDAS ELASTICAS 4 PULGADAS', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false),
  ('35B', 'VENOSETH', 'insumo'::public.categoria_producto, null, 'unidad', 'activo'::public.estado_producto, true, 1, 'unidad', false)
on conflict (codigo) do update set
+  categoria = excluded.categoria, presentacion = excluded.presentacion, unidad_medida = excluded.unidad_medida, estado = excluded.estado,
+  es_consumible = excluded.es_consumible, contenido_por_presentacion = excluded.contenido_por_presentacion,
+  unidad_dispensacion = excluded.unidad_dispensacion, permite_registro_sin_descuento = excluded.permite_registro_sin_descuento;

insert into public.inventario_sede (producto_id, sede_id, existencia_actual, existencia_minima)
select p.id, s.id, v.existencia_actual, v.existencia_minima from (values
  ('31A', 'Z9', 272, 55),
  ('31A', 'Z3', 26, 6),
  ('8A', 'Z9', 677, 136),
  ('8A', 'Z3', 500, 100),
  ('22A', 'Z9', 167, 34),
  ('22A', 'Z3', 46, 10),
  ('9A', 'Z9', 2, 1),
  ('9A', 'Z3', 1, 1),
  ('38A', 'Z9', 27, 6),
  ('38A', 'Z3', 86, 18),
  ('3A', 'Z9', 0, 1),
  ('3A', 'Z3', 21, 5),
  ('33A', 'Z9', 103, 21),
  ('33A', 'Z3', 0, 1),
  ('57A', 'Z9', 10, 2),
  ('57A', 'Z3', 0, 1),
  ('12A', 'Z9', 2, 1),
  ('12A', 'Z3', 1, 1),
  ('47A', 'Z9', 14, 3),
  ('47A', 'Z3', 1, 1),
  ('19A', 'Z9', 107, 22),
  ('19A', 'Z3', 13, 3),
  ('48A', 'Z9', 0, 1),
  ('48A', 'Z3', 11, 3),
  ('59A', 'Z9', 50, 10),
  ('59A', 'Z3', 105, 21),
  ('49A', 'Z9', 32, 7),
  ('49A', 'Z3', 8, 2),
  ('50A', 'Z9', 53, 11),
  ('50A', 'Z3', 0, 1),
  ('MED-AUTO-016', 'Z9', 31, 7),
  ('MED-AUTO-016', 'Z3', 29, 6),
  ('11A', 'Z9', 3, 1),
  ('11A', 'Z3', 3, 1),
  ('39A', 'Z9', 42, 9),
  ('39A', 'Z3', 54, 11),
  ('MED-AUTO-019', 'Z9', 10, 2),
  ('MED-AUTO-019', 'Z3', 7, 2),
  ('7A', 'Z9', 2, 1),
  ('7A', 'Z3', 2, 1),
  ('21A', 'Z9', 125, 25),
  ('21A', 'Z3', 80, 16),
  ('36A', 'Z9', 154, 31),
  ('36A', 'Z3', 80, 16),
  ('MED-AUTO-023', 'Z9', 99, 20),
  ('MED-AUTO-023', 'Z3', 69, 14),
  ('32A', 'Z9', 2, 1),
  ('32A', 'Z3', 2, 1),
  ('40A', 'Z9', 2, 1),
  ('40A', 'Z3', 1, 1),
  ('MED-AUTO-026', 'Z9', 350, 70),
  ('MED-AUTO-026', 'Z3', 107, 22),
  ('45A', 'Z9', 328, 66),
  ('43A', 'Z9', 2, 1),
  ('43A', 'Z3', 0, 1),
  ('34A', 'Z9', 10, 2),
  ('34A', 'Z3', 9, 2),
  ('MED-AUTO-034', 'Z9', 120, 24),
  ('MED-AUTO-034', 'Z3', 154, 31),
  ('23A', 'Z9', 1291, 259),
  ('23A', 'Z3', 146, 30),
  ('55A', 'Z9', 2, 1),
  ('55A', 'Z3', 1, 1),
  ('6A', 'Z9', 424, 85),
  ('6A', 'Z3', 704, 141),
  ('51A', 'Z9', 194, 39),
  ('51A', 'Z3', 34, 7),
  ('30A', 'Z9', 60, 12),
  ('30A', 'Z3', 38, 8),
  ('16A', 'Z9', 75, 15),
  ('16A', 'Z3', 140, 28),
  ('37A', 'Z9', 92, 19),
  ('37A', 'Z3', 29, 6),
  ('52A', 'Z9', 26, 6),
  ('52A', 'Z3', 15, 3),
  ('28A', 'Z9', 217, 44),
  ('28A', 'Z3', 186, 38),
  ('MED-AUTO-044', 'Z9', 293, 59),
  ('MED-AUTO-044', 'Z3', 0, 1),
  ('58A', 'Z9', 26, 6),
  ('58A', 'Z3', 20, 4),
  ('29A', 'Z9', 366, 74),
  ('29A', 'Z3', 177, 36),
  ('20A', 'Z9', 2, 1),
  ('20A', 'Z3', 1, 1),
  ('35A', 'Z9', 0, 1),
  ('35A', 'Z3', 103, 21),
  ('1A', 'Z9', 0, 1),
  ('1A', 'Z3', 1, 1),
  ('4A', 'Z9', 4, 1),
  ('4A', 'Z3', 2, 1),
  ('10A', 'Z9', 50, 10),
  ('10A', 'Z3', 0, 1),
  ('60A', 'Z9', 0, 1),
  ('60A', 'Z3', 9, 2),
  ('18A', 'Z9', 2, 1),
  ('18A', 'Z3', 1, 1),
  ('24A', 'Z9', 80, 16),
  ('24A', 'Z3', 81, 17),
  ('15A', 'Z9', 2, 1),
  ('15A', 'Z3', 2, 1),
  ('17A', 'Z9', 0, 1),
  ('17A', 'Z3', 2, 1),
  ('26A', 'Z9', 10, 2),
  ('26A', 'Z3', 2, 1),
  ('2A', 'Z9', 0, 1),
  ('2A', 'Z3', 23, 5),
  ('53A', 'Z9', 2, 1),
  ('53A', 'Z3', 0, 1),
  ('54A', 'Z9', 10, 2),
  ('54A', 'Z3', 16, 4),
  ('27A', 'Z9', 211, 43),
  ('27A', 'Z3', 163, 33),
  ('13A', 'Z9', 3, 1),
  ('13A', 'Z3', 2, 1),
  ('5A', 'Z9', 120, 24),
  ('5A', 'Z3', 24, 5),
  ('14A', 'Z9', 200, 40),
  ('14A', 'Z3', 106, 22),
  ('25A', 'Z9', 209, 42),
  ('25A', 'Z3', 53, 11),
  ('56A', 'Z9', 32, 7),
  ('56A', 'Z3', 0, 1),
  ('MED-AUTO-067', 'Z3', 2, 1),
  ('MED-AUTO-068', 'Z3', 0, 1),
  ('MED-AUTO-069', 'Z3', 157, 32),
  ('MED-AUTO-070', 'Z3', 160, 32),
  ('MED-AUTO-071', 'Z3', 28, 6),
  ('MED-AUTO-072', 'Z3', 1, 1),
  ('MED-AUTO-073', 'Z3', 2, 1),
  ('MED-AUTO-074', 'Z3', 1, 1),
  ('MED-AUTO-075', 'Z3', 1, 1),
  ('MED-AUTO-076', 'Z3', 32, 7),
  ('1B', 'Z9', 1, 1),
  ('1B', 'Z3', 2, 1),
  ('2B', 'Z9', 0, 1),
  ('2B', 'Z3', 114, 1),
  ('3B', 'Z9', 117, 1),
  ('3B', 'Z3', 125, 1),
  ('4B', 'Z9', 3, 1),
  ('4B', 'Z3', 1, 1),
  ('INS-AUTO-005', 'Z3', 1, 1),
  ('5B', 'Z9', 2, 2),
  ('5B', 'Z3', 1, 2),
  ('6B', 'Z9', 5, 10),
  ('6B', 'Z3', 4, 10),
  ('7B', 'Z9', 14, 25),
  ('7B', 'Z3', 42, 25),
  ('INS-AUTO-009', 'Z9', 19, 25),
  ('INS-AUTO-009', 'Z3', 21, 25),
  ('INS-AUTO-010', 'Z9', 19, 10),
  ('INS-AUTO-010', 'Z3', 25, 10),
  ('INS-AUTO-011', 'Z9', 2, 3),
  ('INS-AUTO-011', 'Z3', 3, 3),
  ('8B', 'Z9', 2, 4),
  ('8B', 'Z3', 1, 4),
  ('INS-AUTO-013', 'Z9', 11, 3),
  ('INS-AUTO-013', 'Z3', 3, 1),
  ('9B', 'Z9', 0, 2),
  ('10B', 'Z9', 2, 1),
  ('10B', 'Z3', 2, 1),
  ('11B', 'Z9', 2, 1),
  ('11B', 'Z3', 1, 1),
  ('INS-AUTO-017', 'Z9', 0, 2),
  ('INS-AUTO-017', 'Z3', 2, 2),
  ('INS-AUTO-018', 'Z3', 2, 1),
  ('12B', 'Z9', 15, 10),
  ('12B', 'Z3', 32, 10),
  ('INS-AUTO-020', 'Z9', 17, 25),
  ('INS-AUTO-020', 'Z3', 26, 25),
  ('INS-AUTO-021', 'Z9', 10, 20),
  ('INS-AUTO-021', 'Z3', 18, 20),
  ('INS-AUTO-022', 'Z3', 38, 8),
  ('13B', 'Z9', 6, 2),
  ('13B', 'Z3', 15, 3),
  ('INS-AUTO-024', 'Z3', 7, 2),
  ('INS-AUTO-025', 'Z3', 3, 1),
  ('INS-AUTO-026', 'Z3', 10, 2),
  ('14B', 'Z9', 200, 300),
  ('14B', 'Z3', 2, 300),
  ('INS-AUTO-028', 'Z3', 13, 3),
  ('15B', 'Z9', 105, 21),
  ('15B', 'Z3', 66, 14),
  ('16B', 'Z9', 20, 40),
  ('16B', 'Z3', 17, 40),
  ('INS-AUTO-031', 'Z9', 82, 100),
  ('INS-AUTO-031', 'Z3', 140, 100),
  ('INS-AUTO-032', 'Z9', 22, 100),
  ('INS-AUTO-032', 'Z3', 195, 100),
  ('17B', 'Z9', 139, 100),
  ('17B', 'Z3', 249, 100),
  ('18B', 'Z9', 650, 130),
  ('18B', 'Z3', 194, 39),
  ('19B', 'Z9', 2, 1),
  ('19B', 'Z3', 1, 1),
  ('20B', 'Z9', 4, 10),
  ('20B', 'Z3', 6, 10),
  ('21B', 'Z9', 0, 2),
  ('22B', 'Z9', 2, 6),
  ('22B', 'Z3', 3, 6),
  ('23B', 'Z9', 0, 1),
  ('23B', 'Z3', 3, 1),
  ('24B', 'Z9', 1, 1),
  ('25B', 'Z9', 0, 10),
  ('25B', 'Z3', 6, 10),
  ('26B', 'Z9', 13, 5),
  ('26B', 'Z3', 6, 5),
  ('INS-AUTO-043', 'Z9', 8, 40),
  ('INS-AUTO-043', 'Z3', 7, 40),
  ('27B', 'Z9', 20, 20),
  ('27B', 'Z3', 35, 20),
  ('28B', 'Z9', 0, 1),
  ('29B', 'Z9', 148, 30),
  ('30B', 'Z9', 248, 50),
  ('30B', 'Z3', 344, 69),
  ('31B', 'Z9', 6, 24),
  ('31B', 'Z3', 8, 24),
  ('32B', 'Z9', 12, 15),
  ('32B', 'Z3', 22, 15),
  ('33B', 'Z9', 80, 95),
  ('33B', 'Z3', 20, 95),
  ('34B', 'Z9', 0, 15),
  ('34B', 'Z3', 27, 15),
  ('35B', 'Z9', 9, 40),
  ('35B', 'Z3', 17, 40)
) v(codigo_producto, codigo_sede, existencia_actual, existencia_minima) join public.productos p on p.codigo = v.codigo_producto join public.sedes s on s.codigo = v.codigo_sede
on conflict (producto_id, sede_id) do update set existencia_actual = excluded.existencia_actual, existencia_minima = excluded.existencia_minima;

insert into public.lotes (producto_id, sede_id, numero_lote, fecha_vencimiento, cantidad_disponible, estado)
select p.id, s.id, null, '2026-07-20'::date, 0, 'vencido'::public.estado_lote
from public.productos p join public.sedes s on s.codigo = 'Z3'
where p.codigo = 'MED-AUTO-068' and not exists (select 1 from public.lotes l where l.producto_id = p.id and l.sede_id = s.id and l.numero_lote is null and l.fecha_vencimiento = '2026-07-20'::date and l.estado = 'vencido');

-- movimientos_inventario se registrarán posteriormente mediante RPC administrativa o script controlado.
commit;
